build: off

artifacts:
- path: bin/kids-ide.exe
  name: kids-ide

before_test:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

- curl -sS -ostack.zip -L --insecure https://get.haskellstack.org/stable/windows-x86_64.zip
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"

    # Override the temp directory to avoid sed escaping issues
    # See https://github.com/haskell/cabal/issues/5386
    TMP: "c:\\tmp"

test_script:

# Install toolchain, but do it silently due to lots of output
- stack setup > nul

- mkdir bin
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack install --no-terminal --test --local-bin-path bin

deploy:
  on:
    branch: master
  provider: S3
  access_key_id:
    secure: a8hgTy6jvE/LTct0bvjHDwpvbwwVLgLrQizDwtmgKMk=
  secret_access_key:
    secure: 5W6G5s8gBqyWDitTR24QBI6PVNetlDI4edWH8Mm9PC8dTK+zDzR43n/QywIn8x3Z
  bucket: www.snoyman.com
  set_public: true
  artifact: kids-ide
  folder: kids-ide
