name: kids-ide
version: 0.1.0.0
github: snoyberg/kids-haskell-ide

dependencies:
- base
- aeson
- wai-extra
- text
- yesod-eventsource
- yesod-core
- conduit
- rio
- wai-handler-launch
- shakespeare
- optparse-simple

executables:
  kids-ide:
    source-dirs: app/
    main: Main.hs
